Document PUT view
openprocurement/openprocurement.contracting.core pull request #38
Opened 2019-01-18 10:15 UTC by bdmbdsm

2019-01-18 13:16 UTC, oleksiyVeretiuk requested changes

2019-01-18 13:16 UTC, oleksiyVeretiuk commented on openprocurement/contracting/core/views/contract_document.py
> +        validators=(validate_file_upload,),
validate_file_update

2019-01-18 13:16 UTC, oleksiyVeretiuk commented on openprocurement/contracting/core/views/contract_document.py
> +        document = self.request.validated['document']
Може викликати Key Error

2019-02-04 13:09 UTC, bdmbdsm commented on openprocurement/contracting/core/views/contract_document.py
> +        document = self.request.validated['document']
Якщо тут скористатись `upload_file`, то результат її роботи треба буде якось прокидати в адаптер, бо вона може робити зміни в документі до збереження. Тому хай краще 500 буде, думаю. І так при нормально завантаженому документі її не виникне.

2019-02-05 14:03 UTC, oleksiyVeretiuk approved these changes

2019-02-08 15:25 UTC, oleksiyVeretiuk approved these changes

2019-02-21 11:06 UTC, Scandie approved these changes

2019-02-21 12:29 UTC, leits approved these changes

2019-02-21 12:54 UTC, merged